name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add steps to build your project and generate the executable
      - name: Build Executable
        run: |
          # Add commands to build your project and generate the .exe file
          # For example, if you're using dotnet, you might use commands like:
          dotnet build -c Release
          dotnet publish -c Release -o ./publish_output

      # Upload the .exe file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyExecutable
          path: ./publish_output/*.exe
