name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH
      
      - name: Restore NuGet packages
        run: nuget restore WpfApp1/WpfApp1.sln

      - name: Build WPF project
        run: |
          $env:Path += ";$env:MSBUILD_PATH"
          msbuild /t:Rebuild /p:Configuration=Release /p:Platform="Any CPU" WpfApp1\WpfApp1\WpfApp1.csproj

      # Add other necessary steps like signing, publishing, etc.

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: WpfAppExecutable
          path: WpfApp1\WpfApp1\bin\Debug\net8.0-windows\WpfApp1.exe
